FROM python:3.12-slim

ARG POETRY_VERSION=2.2.1

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

# نصب curl
RUN apt-get update && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

# نصب Poetry
RUN pip install poetry==$POETRY_VERSION

# غیرفعال کردن venv
RUN poetry config virtualenvs.create false

# کپی فایل‌های dependency
COPY pyproject.toml poetry.lock* ./

# نصب dependencies
RUN poetry install --no-interaction --no-ansi

# کپی سورس
COPY app/ ./app/

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
